title: "Shiva Lakshmanan"
author: "Shiva Lakshmanan"
description: "Data Science/Machine Learning"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About me", file: "README.md"}
  - {title: "Resume", file: "index.html"}
  - {title: "Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:shivalakshmanan1@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/sl2336"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/slaksh/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
